
---
- name: Crea dominio AD
  hosts: domain-controler
  tasks:
    - name: Crea el dominio 'arahant.com.py'
      win_domain:
        dns_domain_name: arahant.com.py
        domain_netbios_name: ARAHANT
        safe_mode_password: abc1234

    - name: Crea un usuario Domain Admins
      win_domain_user:
        name: devopsara
        upn: devopsara@arahant.com.py
        password: 1234abc
        groups: 
          - Domain Admins
