---
- name: Une el windows al dominio AD
  hosts: win10
  tasks:
    - name: Configura el cliente DNS en el SO
      win_dns_client:
        adapter_name: '*'
        ipv4_addresses: 10.22.28.32

    - name: Une el equipo al dominio AD
      win_domain_membership:
        dns_domain_name: arahant.com.py
        hostname: '{{ansible_hostname}}'
        domain_admin_user: ARAHANT\ansiblewin
        domain_admin_password: Temporal01*
        state: domain
      register: domain_join

    - name: Reinicia el servidor si es necesario
      win_shell: Restart-Computer -Force
      when: domain_join.reboot_required
